# ----
# Site

title: DropFL
url: https://dropfl.github.io
languages:
  - ko
  - en
def_lang: ko
google_analytics_key:

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /images/DR.png
description: DropFL
author:
  name: DropFL
  email: dnjsah1230@gmail.com

# -----
# Build

timezone: Asia/Seoul

permalink: pretty

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

collections:
  docs:
    title: Documentation
    permalink: /:path/
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      path: ""
      type: "docs"
    values:
      seo:
        type: Article
      _comments:
        category: Group navigation links with this field
        order: Used to sort links in the navigation
      _options:
        content:
          width: 800
          height: 2000
  -
    scope:
      path: ""
      type: "posts"
    values:
      _comments:
        type: Marks the impact of this release
  -
    scope:
      path: "_docs/en"
    values:
      lang: en
  -
    scope:
      path: "_docs/ko"
    values:
      lang: ko
